# Generated by Django 3.2.7 on 2021-10-25 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_post_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name_on',
            new_name='name_en',
        ),
    ]
